global:
  scrape_interval: 5s # Server 抓取頻率
  external_labels:
    monitor: "my-monitor"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "nginx-exporter-1"
    static_configs:
      - targets: ["nginx-prometheus-exporter-1:9113","nginx-prometheus-exporter-2:9113","nginx-prometheus-exporter-3:9113"]
